name: Memory Domain CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Composer Install
        run: composer install --no-interaction --no-scripts --prefer-dist

      - name: Run Tests
        run: composer phpunit-coverage

